version: '3.7'

services:
  app:
    build:
      context: '.'
      target: 'dev'
    ports:
      - 3000:3000
    command: /bin/sh -c "npm run dev"
    stdin_open: true
    tty: true
    volumes:
      - ./:/usr/src/app
    environment:
      HOST: 0.0.0.0